### ISSUE TITLE
Minor bug found after the song has completed playing

### ISSUE THREAD

**Issue by Ch-sriram** [geekyorion/Audio-Visualiser#1]
After the song completes playing, the pause button acts as the play button and vice-versa. Here's a GIF that explains what I said: ![bug.gif](https://user-images.githubusercontent.com/26023903/75133718-ca5e8f80-5701-11ea-8aa2-2f70f469d816.gif)
Please test it out yourself.

**Comment by geekyorion** [comment]
> After the song completes playing, the pause button acts as the play button and vice-versa. Here's a GIF that explains what I said: ![bug.gif](https://user-images.githubusercontent.com/26023903/75133718-ca5e8f80-5701-11ea-8aa2-2f70f469d816.gif)
> Please test it out yourself.

Thank you for pointing it out. Will fix it :)

**Comment by geekyorion** [comment]
Issue is **resolved** now
changes:
- `ended` event listener is added
